version: '3.8'
services:
  monguito:
    image: mongo:6
    container_name: grpc_monguito
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  grpc_server:
    build: .
    container_name: grpc_server
    depends_on:
      - monguito
    environment:
      - MONGO_URI=mongodb://monguito:27017
      - MONGO_DB=marketplace_db
      - GRPC_PORT=50051
    ports:
      - "50051:50051"

volumes:
  mongo-data: